# Generated by Django 2.2.1 on 2019-05-27 10:50

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('catalog', '0006_auto_20190527_0642'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='isbn',
            field=models.CharField(
                help_text='13 Character <a href="https://www.isbn-international.org/content/what-isbn">ISBN number</a>',
                max_length=15, verbose_name='ISBN'),
        ),
    ]
